version: "3"
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: nest-rabbitmq
    hostname: rabbitmq
    ports:
      - 5671:5671
      - 5672:5672
      - 15672:15672
    networks:
      - microservice-network

  service1:
    build: ./service1
    image: nest-service1
    container_name: nest-service1
    environment:
      QUEUE_IP: rabbitmq
    networks:
      - microservice-network

  service2:
    build: ./service2
    image: nest-service2
    container_name: nest-service2
    environment:
      QUEUE_IP: rabbitmq
    networks:
      - microservice-network

  gateway:
    build: ./gateway
    image: nest-gateway
    container_name: nest-gateway
    environment:
      QUEUE_IP: rabbitmq
    ports:
      - 3000:3000
    networks:
      - microservice-network

networks: 
  microservice-network:
    driver: bridge