apiVersion: v1
kind: ReplicationController
metadata:
  name: gateway
  namespace: micro
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      serviceAccountName: default
      containers:
      - name: gateway
        image: nest-gateway:latest
        imagePullPolicy: Always
        env:
        - name: NODE_ENV
          value: "production"
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 200m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 128Mi