apiVersion: v1
kind: ReplicationController
metadata:
  name: rabbitmq
  namespace: micro
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        imagePullPolicy: Always
        ports:
        - containerPort: 5671
        - containerPort: 5672
        - containerPort: 15672