apiVersion: v1
kind: ReplicationController
metadata:
  name: service2
  namespace: micro
  labels:
    app: service2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service2
  template:
    metadata:
      labels:
        app: service2
    spec:
      containers:
      - name: service2
        image: nest-service2:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 200m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 128Mi