apiVersion: apps/v1
kind: Deployment
metadata:
  name: service2
  namespace: micro
  labels:
    app: service2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service2
  template:
    metadata:
      labels:
        app: service2
    spec:
      serviceAccountName: default
      containers:
      - name: service2
        image: nest-service2:latest
        imagePullPolicy: Always
        env:
        - name: NODE_ENV
          value: "production"
        ports:
        - containerPort: 4001
        resources:
          requests:
            cpu: 200m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 128Mi