apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1
  namespace: micro
  labels:
    app: service1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service1
  template:
    metadata:
      labels:
        app: service1
    spec:
      serviceAccountName: default
      containers:
      - name: service1
        image: nest-service1:latest
        imagePullPolicy: Always
        env:
        - name: NODE_ENV
          value: "production"
        ports:
        - containerPort: 4000
        resources:
          requests:
            cpu: 200m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 128Mi