apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: micro
spec:
  selector:
    app: rabbitmq
  ports:
    - name: "5671"
      port: 5671
      targetPort: 5671
    - name: "5672"
      port: 5672
      targetPort: 5672
    - name: "15672"
      port: 15672
      targetPort: 15672
